### ISSUE TITLE
aeson-casing-0.1.0.0 can't compile its test suite

### ISSUE THREAD

**Issue by peti** [AndrewRademacher/aeson-casing#1]
Citing from http://hydra.cryp.to/build/599153/log/raw:

```
Preprocessing test suite 'casing' for aeson-casing-0.1.0.0...

test/Main.hs:5:18:
    Could not find module ‘Data.Aeson.Casing.Test’
    Perhaps you meant Data.Aeson.Casing (from aeson-casing-0.1.0.0)
    Use -v to see a list of the files searched for.
```

**Comment by erantapaa** [comment]
This is still a problem with aeson-casing-0.1.0.2. The file test/Data/Aeson/Casing/Test.hs is missing from the package uploaded to Hackage.

**Comment by AndrewRademacher** [comment]
Apologies for the delay in response, I've moved the package back under myself so this kind of delay shouldn't happen again. I don't seem to be having any problems running the test suite from my project. Is this issue occurring when you attempt to use aeson-casing as a dependency in another project?

**Comment by AndrewRademacher** [comment]
I've figured out what you mean. I forgot to include the Tests module in the 'other-modules' field on the cabal file.

**Comment by peti** [comment]
Will you release a new version to Hackage?

**Comment by AndrewRademacher** [comment]
Yeah, the latest is already up as `0.1.0.4`. I'm working to get it in stackage as well.
